spring.application.name=salary-management

server.port=8081

# --------------------------------------------------
# H2 Database
# --------------------------------------------------

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Recreate schema for assessment/demo runs
spring.jpa.hibernate.ddl-auto=create

# Load data.sql after schema creation
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# --------------------------------------------------
# JPA
# --------------------------------------------------

spring.jpa.open-in-view=false

# Helpful during development
spring.jpa.show-sql=false